In [1]:
import numpy as np

In [2]:
class ConfigureFirstPoly:
    def __init__(self):
        self.index = -1
        self.size = 1
        self.poly_knowed = 0

def add_array_poly(in_coord, x, y, poly):
    if poly.poly_knowed :
        pass
    elif poly.index == -1 :
        in_coord = np.array( [ [ x , y ] ,] )
        poly.index = poly.index + 1
    else :
        if poly.size != 1 and np.array_equal(in_coord[0],[x, y]) :
            poly.poly_knowed = 1
        elif np.array_equal(in_coord[-1],[x, y]) is False :
            add = np.array([[x,y],])
            in_coord = np.concatenate((in_coord, add))
            poly.index = poly.index + 1
            poly.size = poly.size + 1

    print("c {} i {} size {} knowed {}".format(in_coord,poly.index,poly.size, poly.poly_knowed))
    return in_coord

In [3]:
poly = ConfigureFirstPoly()
in_coord = np.array([[]])

In [15]:
x=5487
y=7517
in_coord = add_array_poly(in_coord,x,y,poly)
in_coord

c [[ 5487  7517]
 [ 6502  5792]
 [ 4478  5976]
 [13524  1990]] i 3 size 4 knowed 1


array([[ 5487,  7517],
       [ 6502,  5792],
       [ 4478,  5976],
       [13524,  1990]])

In [8]:
x=6502
y=5792
in_coord = add_array_poly(in_coord,x,y,poly)
in_coord

c [[5487 7517]
 [6502 5792]] i 1 size 2 knowed 0


array([[5487, 7517],
       [6502, 5792]])

In [11]:
x=4478
y=5976
in_coord = add_array_poly(in_coord,x,y,poly)
in_coord

c [[5487 7517]
 [6502 5792]
 [4478 5976]] i 2 size 3 knowed 0


array([[5487, 7517],
       [6502, 5792],
       [4478, 5976]])

In [14]:
x=13524
y=1990
in_coord = add_array_poly(in_coord,x,y,poly)
in_coord

c [[ 5487  7517]
 [ 6502  5792]
 [ 4478  5976]
 [13524  1990]] i 3 size 4 knowed 0


array([[ 5487,  7517],
       [ 6502,  5792],
       [ 4478,  5976],
       [13524,  1990]])